name       : brotli
version    : 1.0.9
release    : 6
source     :
    - https://github.com/google/brotli/archive/v1.0.9.tar.gz : f9e8d81d0405ba66d181529af42a3354f838c939095ff99930da6aa9cdf6fe46
homepage   : https://www.brotli.org/
license    : MIT
component  : system.utils
emul32     : yes
summary    : Brotli compression format
description: |
    Brotli is a generic-purpose lossless compression algorithm that compresses data using a combination of a modern variant of the LZ77 algorithm, Huffman coding and 2nd order context modeling, with a compression ratio comparable to the best currently available general-purpose compression methods. It is similar in speed with deflate but offers more dense compression.
setup      : |
    %patch -p1 < $pkgfiles/0001-Strip-out-building-of-static-libraries.patch
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 docs/brotli.1 $installdir/usr/share/man/man1/brotli.1
check      : |
    %ninja_check
