name       : brotli
version    : 1.0.7
release    : 4
source     :
    - https://github.com/google/brotli/archive/v1.0.7.tar.gz : 4c61bfb0faca87219ea587326c467b95acb25555b53d1a421ffa3c8a9296ee2c
license    : MIT
component  : system.utils
emul32     : yes
summary    : Brotli compression format
description: |
    Brotli is a generic-purpose lossless compression algorithm that compresses data using a combination of a modern variant of the LZ77 algorithm, Huffman coding and 2nd order context modeling, with a compression ratio comparable to the best currently available general-purpose compression methods. It is similar in speed with deflate but offers more dense compression.
setup      : |
    %patch -p1 < $pkgfiles/0001-Strip-out-building-of-static-libraries.patch
    %cmake_ninja -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
